### ISSUE TITLE
Generar diseño de menu

### ISSUE THREAD

**Issue by eumati** [eumati/norvak#1]
- Generar diseño de iconos de menu "IGUAL" a:
 
![image](https://cloud.githubusercontent.com/assets/8921806/7688377/9d6845ee-fd69-11e4-9b3a-f4f9c52e778c.png)

- en lugar de:
 
![image](https://cloud.githubusercontent.com/assets/8921806/7688385/b3070a2a-fd69-11e4-9017-b13f47b2cad7.png)

**Comment by MoarDante** [comment]
100%
