### ISSUE TITLE
VI Buscar-Filtrar Cliente [18/06]

### ISSUE THREAD

**Issue by eumati** [eumati/norvak#12]
- En el formulario de Clientes, modificar la vista de buscar y filtar, poner los campos de clientes SAE
  * Solo hay que hacer el html, el funcionamiento de js se deja de lado temporalmente

![image](https://cloud.githubusercontent.com/assets/8921806/8145238/71c9b1dc-11c5-11e5-8d00-ec7d99b6b3c4.png)

![image](https://cloud.githubusercontent.com/assets/8921806/8145240/7c50a2a0-11c5-11e5-959d-a043a01ed966.png)

**Comment by MoarDante** [comment]
100%
