### ISSUE TITLE
Consulta de Saldos(Clientes)

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/norvak#26]
![image](https://cloud.githubusercontent.com/assets/8921831/8485603/56915dd0-20c4-11e5-9baf-03c0c14ef5b0.png)

**Comment by VanessaDelAngel** [comment]
* Agregar iconos de información (Con su ventana)
* Filtrar (con su ventana)
* Eliminar Filtros

**Comment by VanessaDelAngel** [comment]
Ventana del icono información del cliente 
![image](https://cloud.githubusercontent.com/assets/8921831/8727224/3233aaac-2ba4-11e5-98f3-dabd2d44ed28.png)

**Comment by VanessaDelAngel** [comment]
Ventana de filtro 
![image](https://cloud.githubusercontent.com/assets/8921831/8727235/4012db16-2ba4-11e5-8694-b180b945f56b.png)

**Comment by MoarDante** [comment]
![image](https://cloud.githubusercontent.com/assets/8039668/8839202/7a697b9e-3090-11e5-874e-316018198fff.png)

**Comment by MoarDante** [comment]
![saldoopciones](https://cloud.githubusercontent.com/assets/8039668/8839255/feba4554-3090-11e5-8770-9c70ef260880.png)
