### ISSUE TITLE
Antigüedad de saldo (Clientes)

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/norvak#30]
*Realizar el siguiente formulario y las ventanas que despliegan sus botones:

![image](https://cloud.githubusercontent.com/assets/8921831/8529886/537d38fe-23e3-11e5-85cc-8dc5639fa869.png)

**Comment by orliitd** [comment]
me pasas la captura del otro modal?

**Comment by orliitd** [comment]
me pasas la captura del otro moda?
 porfa

**Comment by VanessaDelAngel** [comment]
![image](https://cloud.githubusercontent.com/assets/8921831/8558911/61c93030-24cd-11e5-8c04-f4bc9943c3fe.png)

**Comment by VanessaDelAngel** [comment]
Agregar modal de los datos del cliente 
* Icono y funcionalidad del filtro

**Comment by VanessaDelAngel** [comment]
Ventana del filtro 
![image](https://cloud.githubusercontent.com/assets/8921831/8727263/64319bf4-2ba4-11e5-8dd8-7e31c3128416.png)

**Comment by VanessaDelAngel** [comment]
Terminado :+1:
