### ISSUE TITLE
Saldo General Del Cliente (RUTA)

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/norvak#33]
- Generar una ruta en el controlador de clientes para obtener:
 * El saldo general de todas las ventas y sus detalles de un cliente 
  * Primero generar la consulta en Navicat y luego pasarse al controlador
  * En caso de no haber datos en las tablas, hay que insertar algunos de prueba
  * Las tablas que afectan este proceso se pueden preguntar a @VanessaDelAngel

**Comment by OzwaldoC8** [comment]
app.ut.request({url:'clientes/getCobranzaGeneral',data:{desde:0,hasta:10}})

app.ut.request({url:'clientes/getCobranzaGeneral',data:{idCliente:1}})
