### ISSUE TITLE
Recepción de pagos (RUTA)

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/norvak#34]
- Generar una ruta en el controlador de clientes para obtener:
 * Guardar la recepcion de pagos y su dispercion de pagos
  * En caso de no haber datos en las tablas, hay que insertar algunos de prueba
  * Las tablas que afectan este proceso se pueden preguntar a @VanessaDelAngel

**Comment by OzwaldoC8** [comment]
app.ut.request({url:'recepcionPagos/Save',data:json})
