### ISSUE TITLE
Altas de cuentas por cobrar JS

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/norvak#47]
Realizar el js del formulario (en caso de que ya tenga verificar que todo funcione correctamente) esto incluye:
*  Tyas
* Funcionamiento de botones e iconos
* Consultas a la BD (Las rutas necesarias están en el issue con el nombre del formulario (RUTAS), en caso de que no me preguntan a mi o a oz XD)

**Comment by jorges85** [comment]
se empalma en el diseño y falta boton aceptar
