### ISSUE TITLE
Antigüedad Saldo JS

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/norvak#51]
Realizar el js del formulario (en caso de que ya tenga verificar que todo funcione correctamente) esto incluye:
*  Tyas
* Funcionamiento de botones e iconos
* Consultas a la BD (Las rutas necesarias están en el issue con el nombre del formulario (RUTAS), en caso de que no me preguntan a mi o a oz XD)

**Comment by orliitd** [comment]
solo falta implementar lo comentamos el otro dia que dijeron tu y eloy que faltan tablas o algo asi :)

**Comment by VanessaDelAngel** [comment]
Solo falta la funcionalidad del primer icono de los datos del cliente
