### ISSUE TITLE
Filtrar Js [28/07 11:30]

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/norvak#54]
Realizar la funcionalidad de la ventana de filtrar
Y la funcionalidad de la flecha de restaurar debe quitar ese filtro

**Comment by eumati** [comment]
para poder ejecutar el evento buscar en el grid, tienes que usar la funcion del parentview: this.options.parentView.gvGrid.doSearch({id:1})

**Comment by eumati** [comment]
- para hacer multi filtros usar:
 * this.options.parentView.doFilter([{field:'id', query:{op:'>', val:2}}, {field:'id', query:{op:'<', val:5}}])

**Comment by orliitd** [comment]
ya esta solo que se sigue muriendo cuando se filtra por vendedor
