### ISSUE TITLE
Saldo General del cliente JS

### ISSUE THREAD

**Issue by VanessaDelAngel** [eumati/norvak#56]
Solo le falta funcionalidad al filtro de clientes

**Comment by VanessaDelAngel** [comment]
![image](https://cloud.githubusercontent.com/assets/8921831/8944849/987d9978-3548-11e5-95d8-42cb7471f557.png)
![image](https://cloud.githubusercontent.com/assets/8921831/8944854/9e35f61c-3548-11e5-8c71-55f99fb5b192.png)

**Comment by jorges85** [comment]
ya esta listo solo que el filtro desde hasta debe tomar fechas en ves de id's
